type BudgetLineItem = {
  description: string
  amount: number
}

type Milestone = {
  title: string
  targetDate: string
}

type CsrProjectProposalData = {
  projectTitle: string
  ngoName: string
  companyName: string
  scheduleViiCategory: string
  scheduleViiSubCategory: string
  scheduleViiJustification: string
  problemStatement: string
  targetBeneficiaries: string
  activities: string[]
  deliverables: string[]
  totalBudget: number
  budgetBreakdown: BudgetLineItem[]
  startDate: string
  endDate: string
  milestones: Milestone[]
}

export function csrProjectProposalTemplate(data: CsrProjectProposalData): string {
  const formatCrore = (val: number) => `₹${val.toLocaleString("en-IN")}`

  return `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: Georgia, serif; background: #fff; color: #1a1a2e; padding: 60px 72px; font-size: 13px; line-height: 1.6; }
          .header { border-bottom: 3px solid #1a1a2e; padding-bottom: 20px; margin-bottom: 36px; display: flex; justify-content: space-between; align-items: flex-end; }
          .header h1 { font-size: 20px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; }
          .header p { font-size: 11px; color: #555; margin-top: 4px; }
          .header-right { font-size: 11px; color: #555; text-align: right; }
          .section { margin-bottom: 32px; }
          .section-title { font-size: 10px; font-weight: bold; letter-spacing: 2px; text-transform: uppercase; color: #888; margin-bottom: 12px; padding-bottom: 4px; border-bottom: 1px solid #e0e0e0; }
          .field-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px 32px; }
          .field { display: flex; flex-direction: column; gap: 3px; margin-bottom: 12px; }
          .field-label { font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #888; }
          .field-value { font-size: 14px; color: #1a1a2e; font-weight: 500; }
          .prose { font-size: 13px; color: #333; line-height: 1.8; }
          ul { padding-left: 18px; margin-top: 6px; }
          li { font-size: 13px; color: #333; margin-bottom: 4px; }
          table { width: 100%; border-collapse: collapse; font-size: 12px; }
          th { text-align: left; font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #888; padding: 8px 12px; border-bottom: 1px solid #e0e0e0; }
          td { padding: 10px 12px; border-bottom: 1px solid #f0f0f0; color: #1a1a2e; }
          tr:last-child td { border-bottom: none; }
          .total-row td { font-weight: bold; background: #f7f8fc; border-top: 1px solid #e0e0e0; }
          .vii-box { background: #f0f4ff; border: 1px solid #c7d2fe; border-radius: 4px; padding: 16px 20px; }
          .vii-box .field { margin-bottom: 10px; }
          .footer { margin-top: 60px; padding-top: 16px; border-top: 1px solid #e0e0e0; display: flex; justify-content: space-between; font-size: 10px; color: #aaa; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1>CSR Project Proposal</h1>
            <p>Auto-generated by Navadrishti — Companies Act 2013, Section 135</p>
          </div>
          <div class="header-right">
            Generated: ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}
          </div>
        </div>

        <div class="section">
          <div class="section-title">A. Identification</div>
          <div class="field-grid">
            <div class="field">
              <span class="field-label">Project Title</span>
              <span class="field-value">${data.projectTitle}</span>
            </div>
            <div class="field">
              <span class="field-label">Company</span>
              <span class="field-value">${data.companyName}</span>
            </div>
            <div class="field">
              <span class="field-label">Implementing NGO</span>
              <span class="field-value">${data.ngoName}</span>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">B. Schedule VII Mapping</div>
          <div class="vii-box">
            <div class="field">
              <span class="field-label">Category</span>
              <span class="field-value">${data.scheduleViiCategory}</span>
            </div>
            <div class="field">
              <span class="field-label">Sub-Category</span>
              <span class="field-value">${data.scheduleViiSubCategory}</span>
            </div>
            <div class="field">
              <span class="field-label">Justification</span>
              <p class="prose">${data.scheduleViiJustification}</p>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">C. Problem Definition</div>
          <div class="field">
            <span class="field-label">Problem Statement</span>
            <p class="prose">${data.problemStatement}</p>
          </div>
          <div class="field">
            <span class="field-label">Target Beneficiaries</span>
            <p class="prose">${data.targetBeneficiaries}</p>
          </div>
        </div>

        <div class="section">
          <div class="section-title">D. Execution Plan</div>
          <div class="field">
            <span class="field-label">Activities</span>
            <ul>${data.activities.map(a => `<li>${a}</li>`).join("")}</ul>
          </div>
          <div class="field">
            <span class="field-label">Deliverables</span>
            <ul>${data.deliverables.map(d => `<li>${d}</li>`).join("")}</ul>
          </div>
        </div>

        <div class="section">
          <div class="section-title">E. Budget</div>
          <table>
            <thead>
              <tr>
                <th>Description</th>
                <th style="text-align: right;">Amount</th>
              </tr>
            </thead>
            <tbody>
              ${data.budgetBreakdown.map(b => `
                <tr>
                  <td>${b.description}</td>
                  <td style="text-align: right;">${formatCrore(b.amount)}</td>
                </tr>
              `).join("")}
              <tr class="total-row">
                <td>Total Budget</td>
                <td style="text-align: right;">${formatCrore(data.totalBudget)}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="section">
          <div class="section-title">F. Timeline</div>
          <div class="field-grid" style="margin-bottom: 16px;">
            <div class="field">
              <span class="field-label">Start Date</span>
              <span class="field-value">${data.startDate}</span>
            </div>
            <div class="field">
              <span class="field-label">End Date</span>
              <span class="field-value">${data.endDate}</span>
            </div>
          </div>
          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>Milestone</th>
                <th>Target Date</th>
              </tr>
            </thead>
            <tbody>
              ${data.milestones.map((m, i) => `
                <tr>
                  <td>${i + 1}</td>
                  <td>${m.title}</td>
                  <td>${m.targetDate}</td>
                </tr>
              `).join("")}
            </tbody>
          </table>
        </div>

        <div class="footer">
          <span>Navadrishti Document Generation System</span>
          <span>CSR_PROJECT_PROPOSAL — ${data.projectTitle}</span>
        </div>
      </body>
    </html>
  `
}