type AuditExpenseItem = {
  description: string
  certifiedAmount: number
}

type AuditCertificateData = {
  ngoName: string
  projectTitle: string
  companyName: string
  auditPeriod: string
  totalCertifiedExpenses: number
  expenseItems: AuditExpenseItem[]
  udin: string
  caName: string
  caMembershipNumber: string
  caFirmName: string
  caFirmRegistrationNumber: string
  auditDate: string
}

export function auditCertificateTemplate(data: AuditCertificateData): string {
  const fmt = (val: number) => `₹${val.toLocaleString("en-IN")}`

  return `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: Georgia, serif; background: #fff; color: #1a1a2e; padding: 60px 72px; font-size: 13px; line-height: 1.6; }
          .header { border-bottom: 3px solid #1a1a2e; padding-bottom: 20px; margin-bottom: 36px; display: flex; justify-content: space-between; align-items: flex-end; }
          .header h1 { font-size: 20px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; }
          .header p { font-size: 11px; color: #555; margin-top: 4px; }
          .header-right { font-size: 11px; color: #555; text-align: right; }
          .section { margin-bottom: 32px; }
          .section-title { font-size: 10px; font-weight: bold; letter-spacing: 2px; text-transform: uppercase; color: #888; margin-bottom: 12px; padding-bottom: 4px; border-bottom: 1px solid #e0e0e0; }
          .field-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px 32px; }
          .field { display: flex; flex-direction: column; gap: 3px; margin-bottom: 12px; }
          .field-label { font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #888; }
          .field-value { font-size: 14px; color: #1a1a2e; font-weight: 500; }
          .udin-box { background: #f0f4ff; border: 1px solid #c7d2fe; border-radius: 4px; padding: 14px 18px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: center; }
          .udin-label { font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #3730a3; }
          .udin-value { font-size: 15px; font-weight: bold; color: #3730a3; font-family: monospace; }
          table { width: 100%; border-collapse: collapse; font-size: 12px; }
          th { text-align: left; font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #888; padding: 8px 12px; border-bottom: 1px solid #e0e0e0; }
          td { padding: 10px 12px; border-bottom: 1px solid #f0f0f0; color: #1a1a2e; }
          tr:last-child td { border-bottom: none; }
          .total-row td { font-weight: bold; background: #f7f8fc; border-top: 1px solid #e0e0e0; }
          .ca-block { margin-top: 48px; border-top: 1px solid #1a1a2e; padding-top: 12px; max-width: 280px; }
          .ca-name { font-size: 14px; font-weight: bold; }
          .ca-detail { font-size: 11px; color: #555; margin-top: 2px; }
          .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e0e0e0; display: flex; justify-content: space-between; font-size: 10px; color: #aaa; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1>Audit Certificate</h1>
            <p>Auto-generated by Navadrishti — Audit Period: ${data.auditPeriod}</p>
          </div>
          <div class="header-right">
            Generated: ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}
          </div>
        </div>

        <div class="section">
          <div class="field-grid">
            <div class="field">
              <span class="field-label">NGO</span>
              <span class="field-value">${data.ngoName}</span>
            </div>
            <div class="field">
              <span class="field-label">Company</span>
              <span class="field-value">${data.companyName}</span>
            </div>
            <div class="field">
              <span class="field-label">Project</span>
              <span class="field-value">${data.projectTitle}</span>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">UDIN</div>
          <div class="udin-box">
            <span class="udin-label">Unique Document Identification Number</span>
            <span class="udin-value">${data.udin}</span>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Certified Expenses</div>
          <table>
            <thead>
              <tr>
                <th>Description</th>
                <th style="text-align: right;">Certified Amount</th>
              </tr>
            </thead>
            <tbody>
              ${data.expenseItems.map(e => `
                <tr>
                  <td>${e.description}</td>
                  <td style="text-align: right;">${fmt(e.certifiedAmount)}</td>
                </tr>
              `).join("")}
              <tr class="total-row">
                <td>Total Certified</td>
                <td style="text-align: right;">${fmt(data.totalCertifiedExpenses)}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="ca-block">
          <div class="ca-name">${data.caName}</div>
          <div class="ca-detail">M. No: ${data.caMembershipNumber}</div>
          <div class="ca-detail">${data.caFirmName}</div>
          <div class="ca-detail">Firm Reg. No: ${data.caFirmRegistrationNumber}</div>
          <div class="ca-detail">Date: ${data.auditDate}</div>
        </div>

        <div class="footer">
          <span>Navadrishti Document Generation System</span>
          <span>AUDIT_CERTIFICATE — ${data.projectTitle}</span>
        </div>
      </body>
    </html>
  `
}