type OutcomeItem = {
  indicator: string
  target: string
  achieved: string
}

type ImpactAssessmentData = {
  projectTitle: string
  ngoName: string
  companyName: string
  projectPeriod: string
  beneficiariesReached: number
  targetBeneficiaries: number
  outcomesAchieved: OutcomeItem[]
  beforeDescription: string
  afterDescription: string
  narrativeSummary: string
}

export function impactAssessmentTemplate(data: ImpactAssessmentData): string {
  const pct = Math.round((data.beneficiariesReached / data.targetBeneficiaries) * 100)

  return `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: Georgia, serif; background: #fff; color: #1a1a2e; padding: 60px 72px; font-size: 13px; line-height: 1.6; }
          .header { border-bottom: 3px solid #1a1a2e; padding-bottom: 20px; margin-bottom: 36px; display: flex; justify-content: space-between; align-items: flex-end; }
          .header h1 { font-size: 20px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; }
          .header p { font-size: 11px; color: #555; margin-top: 4px; }
          .header-right { font-size: 11px; color: #555; text-align: right; }
          .section { margin-bottom: 32px; }
          .section-title { font-size: 10px; font-weight: bold; letter-spacing: 2px; text-transform: uppercase; color: #888; margin-bottom: 12px; padding-bottom: 4px; border-bottom: 1px solid #e0e0e0; }
          .field-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px 32px; }
          .field { display: flex; flex-direction: column; gap: 3px; margin-bottom: 12px; }
          .field-label { font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #888; }
          .field-value { font-size: 14px; color: #1a1a2e; font-weight: 500; }
          .beneficiary-card { background: #f0f4ff; border: 1px solid #c7d2fe; border-radius: 4px; padding: 20px; text-align: center; margin-bottom: 24px; }
          .bene-number { font-size: 36px; font-weight: bold; color: #3730a3; }
          .bene-label { font-size: 11px; color: #555; margin-top: 4px; }
          .bene-pct { font-size: 14px; color: #3730a3; font-weight: bold; margin-top: 8px; }
          .before-after { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
          .ba-card { border: 1px solid #e0e0e0; border-radius: 4px; padding: 16px; }
          .ba-title { font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #888; margin-bottom: 8px; }
          .ba-content { font-size: 13px; color: #333; line-height: 1.7; }
          .prose { font-size: 13px; color: #333; line-height: 1.8; }
          table { width: 100%; border-collapse: collapse; font-size: 12px; }
          th { text-align: left; font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #888; padding: 8px 12px; border-bottom: 1px solid #e0e0e0; }
          td { padding: 10px 12px; border-bottom: 1px solid #f0f0f0; color: #1a1a2e; }
          tr:last-child td { border-bottom: none; }
          .footer { margin-top: 60px; padding-top: 16px; border-top: 1px solid #e0e0e0; display: flex; justify-content: space-between; font-size: 10px; color: #aaa; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1>Impact Assessment Report</h1>
            <p>Auto-generated by Navadrishti — Project Period: ${data.projectPeriod}</p>
          </div>
          <div class="header-right">
            Generated: ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}
          </div>
        </div>

        <div class="section">
          <div class="field-grid">
            <div class="field">
              <span class="field-label">Project</span>
              <span class="field-value">${data.projectTitle}</span>
            </div>
            <div class="field">
              <span class="field-label">NGO</span>
              <span class="field-value">${data.ngoName}</span>
            </div>
            <div class="field">
              <span class="field-label">Company</span>
              <span class="field-value">${data.companyName}</span>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Beneficiaries Reached</div>
          <div class="beneficiary-card">
            <div class="bene-number">${data.beneficiariesReached.toLocaleString("en-IN")}</div>
            <div class="bene-label">of ${data.targetBeneficiaries.toLocaleString("en-IN")} targeted</div>
            <div class="bene-pct">${pct}% target achieved</div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Outcomes Achieved</div>
          <table>
            <thead>
              <tr><th>Indicator</th><th>Target</th><th>Achieved</th></tr>
            </thead>
            <tbody>
              ${data.outcomesAchieved.map(o => `
                <tr>
                  <td>${o.indicator}</td>
                  <td>${o.target}</td>
                  <td>${o.achieved}</td>
                </tr>
              `).join("")}
            </tbody>
          </table>
        </div>

        <div class="section">
          <div class="section-title">Before / After Comparison</div>
          <div class="before-after">
            <div class="ba-card">
              <div class="ba-title">Before</div>
              <div class="ba-content">${data.beforeDescription}</div>
            </div>
            <div class="ba-card">
              <div class="ba-title">After</div>
              <div class="ba-content">${data.afterDescription}</div>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Narrative Summary</div>
          <p class="prose">${data.narrativeSummary}</p>
        </div>

        <div class="footer">
          <span>Navadrishti Document Generation System</span>
          <span>IMPACT_ASSESSMENT — ${data.projectTitle}</span>
        </div>
      </body>
    </html>
  `
}