type MilestoneStatus = {
  title: string
  status: "completed" | "in-progress" | "pending"
  completionPercentage: number
}

type EvidenceItem = {
  type: "media" | "gps" | "timestamp" | "document"
  description: string
  url?: string
  timestamp?: string
  gpsCoordinates?: string
}

type ProgressReportData = {
  projectTitle: string
  ngoName: string
  companyName: string
  reportingPeriod: string
  reportNumber: number
  milestoneStatuses: MilestoneStatus[]
  workCompleted: string
  evidence: EvidenceItem[]
}

export function progressReportTemplate(data: ProgressReportData): string {
  const statusColor = (status: MilestoneStatus["status"]) => {
    if (status === "completed") return { bg: "#e8f5e9", border: "#a5d6a7", text: "#2e7d32" }
    if (status === "in-progress") return { bg: "#fff8e1", border: "#ffe082", text: "#f57f17" }
    return { bg: "#f5f5f5", border: "#e0e0e0", text: "#757575" }
  }

  const evidenceIcon = (type: EvidenceItem["type"]) => {
    if (type === "media") return "📷"
    if (type === "gps") return "📍"
    if (type === "timestamp") return "🕐"
    return "📄"
  }

  return `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: Georgia, serif; background: #fff; color: #1a1a2e; padding: 60px 72px; font-size: 13px; line-height: 1.6; }
          .header { border-bottom: 3px solid #1a1a2e; padding-bottom: 20px; margin-bottom: 36px; display: flex; justify-content: space-between; align-items: flex-end; }
          .header h1 { font-size: 20px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; }
          .header p { font-size: 11px; color: #555; margin-top: 4px; }
          .header-right { font-size: 11px; color: #555; text-align: right; }
          .section { margin-bottom: 32px; }
          .section-title { font-size: 10px; font-weight: bold; letter-spacing: 2px; text-transform: uppercase; color: #888; margin-bottom: 12px; padding-bottom: 4px; border-bottom: 1px solid #e0e0e0; }
          .field-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px 32px; }
          .field { display: flex; flex-direction: column; gap: 3px; margin-bottom: 12px; }
          .field-label { font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #888; }
          .field-value { font-size: 14px; color: #1a1a2e; font-weight: 500; }
          .prose { font-size: 13px; color: #333; line-height: 1.8; }
          .milestone-item { display: flex; justify-content: space-between; align-items: center; padding: 12px 16px; border: 1px solid #e0e0e0; border-radius: 4px; margin-bottom: 8px; }
          .milestone-title { font-size: 13px; font-weight: 500; color: #1a1a2e; }
          .milestone-right { display: flex; align-items: center; gap: 12px; }
          .milestone-pct { font-size: 12px; color: #555; }
          .status-badge { font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; padding: 3px 8px; border-radius: 2px; }
          .evidence-item { display: flex; gap: 12px; align-items: flex-start; padding: 10px 0; border-bottom: 1px solid #f0f0f0; }
          .evidence-item:last-child { border-bottom: none; }
          .evidence-icon { font-size: 16px; }
          .evidence-desc { font-size: 12px; color: #333; }
          .evidence-meta { font-size: 11px; color: #888; margin-top: 2px; }
          .footer { margin-top: 60px; padding-top: 16px; border-top: 1px solid #e0e0e0; display: flex; justify-content: space-between; font-size: 10px; color: #aaa; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1>Progress Report #${data.reportNumber}</h1>
            <p>Auto-generated by Navadrishti — Reporting Period: ${data.reportingPeriod}</p>
          </div>
          <div class="header-right">
            Generated: ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}
          </div>
        </div>

        <div class="section">
          <div class="field-grid">
            <div class="field">
              <span class="field-label">Project</span>
              <span class="field-value">${data.projectTitle}</span>
            </div>
            <div class="field">
              <span class="field-label">NGO</span>
              <span class="field-value">${data.ngoName}</span>
            </div>
            <div class="field">
              <span class="field-label">Company</span>
              <span class="field-value">${data.companyName}</span>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Milestone Status</div>
          ${data.milestoneStatuses.map(m => {
            const c = statusColor(m.status)
            return `
              <div class="milestone-item">
                <span class="milestone-title">${m.title}</span>
                <div class="milestone-right">
                  <span class="milestone-pct">${m.completionPercentage}%</span>
                  <span class="status-badge" style="background:${c.bg}; border:1px solid ${c.border}; color:${c.text};">${m.status}</span>
                </div>
              </div>
            `
          }).join("")}
        </div>

        <div class="section">
          <div class="section-title">Work Completed</div>
          <p class="prose">${data.workCompleted}</p>
        </div>

        <div class="section">
          <div class="section-title">Evidence</div>
          ${data.evidence.map(e => `
            <div class="evidence-item">
              <span class="evidence-icon">${evidenceIcon(e.type)}</span>
              <div>
                <div class="evidence-desc">${e.description}</div>
                <div class="evidence-meta">
                  ${e.timestamp ? `Timestamp: ${e.timestamp}` : ""}
                  ${e.gpsCoordinates ? ` | GPS: ${e.gpsCoordinates}` : ""}
                  ${e.url ? ` | <a href="${e.url}">${e.url}</a>` : ""}
                </div>
              </div>
            </div>
          `).join("")}
        </div>

        <div class="footer">
          <span>Navadrishti Document Generation System</span>
          <span>PROGRESS_REPORT_${data.reportNumber} — ${data.projectTitle}</span>
        </div>
      </body>
    </html>
  `
}