type ExpenseItem = {
  description: string
  amount: number
  invoiceRef?: string
}

type UtilizationCertificateData = {
  ngoName: string
  projectTitle: string
  companyName: string
  reportingPeriod: string
  fundsReceived: number
  fundsUtilized: number
  balance: number
  expenseBreakdown: ExpenseItem[]
}

export function utilizationCertificateTemplate(data: UtilizationCertificateData): string {
  const fmt = (val: number) => `₹${val.toLocaleString("en-IN")}`

  return `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: Georgia, serif; background: #fff; color: #1a1a2e; padding: 60px 72px; font-size: 13px; line-height: 1.6; }
          .header { border-bottom: 3px solid #1a1a2e; padding-bottom: 20px; margin-bottom: 36px; display: flex; justify-content: space-between; align-items: flex-end; }
          .header h1 { font-size: 20px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; }
          .header p { font-size: 11px; color: #555; margin-top: 4px; }
          .header-right { font-size: 11px; color: #555; text-align: right; }
          .section { margin-bottom: 32px; }
          .section-title { font-size: 10px; font-weight: bold; letter-spacing: 2px; text-transform: uppercase; color: #888; margin-bottom: 12px; padding-bottom: 4px; border-bottom: 1px solid #e0e0e0; }
          .field-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px 32px; }
          .field { display: flex; flex-direction: column; gap: 3px; }
          .field-label { font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #888; }
          .field-value { font-size: 14px; color: #1a1a2e; font-weight: 500; }
          .summary-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px; margin-bottom: 24px; }
          .summary-card { background: #f7f8fc; border: 1px solid #e0e0e0; border-radius: 4px; padding: 14px; }
          .summary-card .field-label { margin-bottom: 6px; }
          .summary-card .field-value { font-size: 16px; font-weight: bold; }
          .summary-card.balance { background: ${data.balance > 0 ? "#f1f8f1" : "#f7f8fc"}; border-color: ${data.balance > 0 ? "#a5d6a7" : "#e0e0e0"}; }
          table { width: 100%; border-collapse: collapse; font-size: 12px; }
          th { text-align: left; font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #888; padding: 8px 12px; border-bottom: 1px solid #e0e0e0; }
          td { padding: 10px 12px; border-bottom: 1px solid #f0f0f0; color: #1a1a2e; }
          tr:last-child td { border-bottom: none; }
          .total-row td { font-weight: bold; background: #f7f8fc; border-top: 1px solid #e0e0e0; }
          .footer { margin-top: 60px; padding-top: 16px; border-top: 1px solid #e0e0e0; display: flex; justify-content: space-between; font-size: 10px; color: #aaa; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1>Utilization Certificate</h1>
            <p>Auto-generated by Navadrishti — Reporting Period: ${data.reportingPeriod}</p>
          </div>
          <div class="header-right">
            Generated: ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}
          </div>
        </div>

        <div class="section">
          <div class="field-grid">
            <div class="field">
              <span class="field-label">NGO</span>
              <span class="field-value">${data.ngoName}</span>
            </div>
            <div class="field">
              <span class="field-label">Company</span>
              <span class="field-value">${data.companyName}</span>
            </div>
            <div class="field">
              <span class="field-label">Project</span>
              <span class="field-value">${data.projectTitle}</span>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Fund Summary</div>
          <div class="summary-grid">
            <div class="summary-card">
              <div class="field-label">Funds Received</div>
              <div class="field-value">${fmt(data.fundsReceived)}</div>
            </div>
            <div class="summary-card">
              <div class="field-label">Funds Utilized</div>
              <div class="field-value">${fmt(data.fundsUtilized)}</div>
            </div>
            <div class="summary-card balance">
              <div class="field-label">Balance</div>
              <div class="field-value">${fmt(data.balance)}</div>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Expense Breakdown</div>
          <table>
            <thead>
              <tr>
                <th>Description</th>
                <th>Invoice Ref</th>
                <th style="text-align: right;">Amount</th>
              </tr>
            </thead>
            <tbody>
              ${data.expenseBreakdown.map(e => `
                <tr>
                  <td>${e.description}</td>
                  <td>${e.invoiceRef ?? "—"}</td>
                  <td style="text-align: right;">${fmt(e.amount)}</td>
                </tr>
              `).join("")}
              <tr class="total-row">
                <td colspan="2">Total Utilized</td>
                <td style="text-align: right;">${fmt(data.fundsUtilized)}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="footer">
          <span>Navadrishti Document Generation System</span>
          <span>UTILIZATION_CERTIFICATE — ${data.projectTitle}</span>
        </div>
      </body>
    </html>
  `
}