type ScheduleViiSector = {
  category: string
  subCategory: string
}

type PastProject = {
  title: string
  year: string
  company: string
  budget: number
}

type NgoCapabilityStatementData = {
  legalName: string
  registrationNumber: string
  sectorsWorked: ScheduleViiSector[]
  pastProjects: PastProject[]
  geographicCoverage: string[]
  executionCapacity: string
  teamStrength: number
}

export function ngoCapabilityStatementTemplate(data: NgoCapabilityStatementData): string {
  const formatCrore = (val: number) => `₹${val.toLocaleString("en-IN")} Cr`

  return `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: Georgia, serif; background: #fff; color: #1a1a2e; padding: 60px 72px; font-size: 13px; line-height: 1.6; }
          .header { border-bottom: 3px solid #1a1a2e; padding-bottom: 20px; margin-bottom: 36px; display: flex; justify-content: space-between; align-items: flex-end; }
          .header h1 { font-size: 20px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; }
          .header p { font-size: 11px; color: #555; margin-top: 4px; }
          .header-right { font-size: 11px; color: #555; text-align: right; }
          .section { margin-bottom: 32px; }
          .section-title { font-size: 10px; font-weight: bold; letter-spacing: 2px; text-transform: uppercase; color: #888; margin-bottom: 12px; padding-bottom: 4px; border-bottom: 1px solid #e0e0e0; }
          .field { display: flex; flex-direction: column; gap: 3px; margin-bottom: 14px; }
          .field-label { font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #888; }
          .field-value { font-size: 14px; color: #1a1a2e; font-weight: 500; }
          .tag-list { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 4px; }
          .tag { background: #f0f4ff; border: 1px solid #c7d2fe; color: #3730a3; font-size: 11px; padding: 3px 10px; border-radius: 2px; }
          table { width: 100%; border-collapse: collapse; font-size: 12px; }
          th { text-align: left; font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #888; padding: 8px 12px; border-bottom: 1px solid #e0e0e0; }
          td { padding: 10px 12px; border-bottom: 1px solid #f0f0f0; color: #1a1a2e; }
          tr:last-child td { border-bottom: none; }
          .footer { margin-top: 60px; padding-top: 16px; border-top: 1px solid #e0e0e0; display: flex; justify-content: space-between; font-size: 10px; color: #aaa; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1>NGO Capability Statement</h1>
            <p>Auto-generated by Navadrishti — Schedule VII Sector Mapping</p>
          </div>
          <div class="header-right">
            Generated: ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}
          </div>
        </div>

        <div class="section">
          <div class="field">
            <span class="field-label">Organisation Name</span>
            <span class="field-value">${data.legalName}</span>
          </div>
          <div class="field">
            <span class="field-label">Registration Number</span>
            <span class="field-value">${data.registrationNumber}</span>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Sectors Worked (Schedule VII)</div>
          <div class="tag-list">
            ${data.sectorsWorked.map(s => `<span class="tag">${s.category} — ${s.subCategory}</span>`).join("")}
          </div>
        </div>

        <div class="section">
          <div class="section-title">Past Projects</div>
          <table>
            <thead>
              <tr>
                <th>Project Title</th>
                <th>Year</th>
                <th>Company Partner</th>
                <th>Budget</th>
              </tr>
            </thead>
            <tbody>
              ${data.pastProjects.map(p => `
                <tr>
                  <td>${p.title}</td>
                  <td>${p.year}</td>
                  <td>${p.company}</td>
                  <td>${formatCrore(p.budget)}</td>
                </tr>
              `).join("")}
            </tbody>
          </table>
        </div>

        <div class="section">
          <div class="section-title">Operational Details</div>
          <div class="field">
            <span class="field-label">Geographic Coverage</span>
            <div class="tag-list">
              ${data.geographicCoverage.map(g => `<span class="tag">${g}</span>`).join("")}
            </div>
          </div>
          <div class="field">
            <span class="field-label">Execution Capacity</span>
            <span class="field-value">${data.executionCapacity}</span>
          </div>
          <div class="field">
            <span class="field-label">Team Strength</span>
            <span class="field-value">${data.teamStrength} members</span>
          </div>
        </div>

        <div class="footer">
          <span>Navadrishti Document Generation System</span>
          <span>NGO_CAPABILITY_STATEMENT — ${data.registrationNumber}</span>
        </div>
      </body>
    </html>
  `
}