type IndividualParticipationAgreementData = {
  individualName: string
  idProof?: string
  role: string
  projectTitle: string
  ngoName: string
  startDate: string
  endDate: string
  compensationAmount?: number
  compensationNotes?: string
  attendanceRequirements: string
  codeOfConduct: string[]
  agreementDate: string
}

export function individualParticipationAgreementTemplate(data: IndividualParticipationAgreementData): string {
  const hasCompensation = data.compensationAmount && data.compensationAmount > 0

  return `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: Georgia, serif; background: #fff; color: #1a1a2e; padding: 60px 72px; font-size: 13px; line-height: 1.6; }
          .header { border-bottom: 3px solid #1a1a2e; padding-bottom: 20px; margin-bottom: 36px; display: flex; justify-content: space-between; align-items: flex-end; }
          .header h1 { font-size: 20px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; }
          .header p { font-size: 11px; color: #555; margin-top: 4px; }
          .header-right { font-size: 11px; color: #555; text-align: right; }
          .section { margin-bottom: 32px; }
          .section-title { font-size: 10px; font-weight: bold; letter-spacing: 2px; text-transform: uppercase; color: #888; margin-bottom: 12px; padding-bottom: 4px; border-bottom: 1px solid #e0e0e0; }
          .field-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px 32px; }
          .field { display: flex; flex-direction: column; gap: 3px; margin-bottom: 12px; }
          .field-label { font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #888; }
          .field-value { font-size: 14px; color: #1a1a2e; font-weight: 500; }
          .field-value.muted { color: #999; font-style: italic; font-size: 12px; }
          .prose { font-size: 13px; color: #333; line-height: 1.8; }
          ul { padding-left: 18px; margin-top: 6px; }
          li { font-size: 13px; color: #333; margin-bottom: 4px; }
          .compensation-box { background: #f7f8fc; border: 1px solid #e0e0e0; border-radius: 4px; padding: 14px 18px; }
          .signatures { display: grid; grid-template-columns: 1fr 1fr; gap: 48px; margin-top: 60px; }
          .sig-block { border-top: 1px solid #1a1a2e; padding-top: 8px; }
          .sig-name { font-size: 12px; font-weight: bold; }
          .sig-detail { font-size: 11px; color: #555; }
          .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e0e0e0; display: flex; justify-content: space-between; font-size: 10px; color: #aaa; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1>Individual Participation Agreement</h1>
            <p>Auto-generated by Navadrishti | Date: ${data.agreementDate}</p>
          </div>
          <div class="header-right">
            Generated: ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}
          </div>
        </div>

        <div class="section">
          <div class="section-title">Participant Details</div>
          <div class="field-grid">
            <div class="field">
              <span class="field-label">Full Name</span>
              <span class="field-value">${data.individualName}</span>
            </div>
            <div class="field">
              <span class="field-label">ID Proof</span>
              <span class="field-value ${!data.idProof ? "muted" : ""}">${data.idProof ?? "To be submitted"}</span>
            </div>
            <div class="field">
              <span class="field-label">Role</span>
              <span class="field-value">${data.role}</span>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Engagement Details</div>
          <div class="field-grid">
            <div class="field">
              <span class="field-label">Project</span>
              <span class="field-value">${data.projectTitle}</span>
            </div>
            <div class="field">
              <span class="field-label">Organisation</span>
              <span class="field-value">${data.ngoName}</span>
            </div>
            <div class="field">
              <span class="field-label">Start Date</span>
              <span class="field-value">${data.startDate}</span>
            </div>
            <div class="field">
              <span class="field-label">End Date</span>
              <span class="field-value">${data.endDate}</span>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Compensation</div>
          <div class="compensation-box">
            <div class="field">
              <span class="field-label">Type</span>
              <span class="field-value">${hasCompensation ? "Wage-based" : "Voluntary (No Compensation)"}</span>
            </div>
            ${hasCompensation ? `
              <div class="field">
                <span class="field-label">Amount</span>
                <span class="field-value">₹${data.compensationAmount!.toLocaleString("en-IN")}</span>
              </div>
              ${data.compensationNotes ? `
                <div class="field">
                  <span class="field-label">Notes</span>
                  <p class="prose">${data.compensationNotes}</p>
                </div>
              ` : ""}
            ` : ""}
          </div>
        </div>

        <div class="section">
          <div class="section-title">Attendance Requirements</div>
          <p class="prose">${data.attendanceRequirements}</p>
        </div>

        <div class="section">
          <div class="section-title">Code of Conduct</div>
          <ul>${data.codeOfConduct.map(c => `<li>${c}</li>`).join("")}</ul>
        </div>

        <div class="signatures">
          <div class="sig-block">
            <div class="sig-name">${data.individualName}</div>
            <div class="sig-detail">Participant</div>
            <div class="sig-detail">Date: _______________</div>
          </div>
          <div class="sig-block">
            <div class="sig-name">Authorised Signatory</div>
            <div class="sig-detail">${data.ngoName}</div>
            <div class="sig-detail">Date: _______________</div>
          </div>
        </div>

        <div class="footer">
          <span>Navadrishti Document Generation System</span>
          <span>INDIVIDUAL_PARTICIPATION — ${data.individualName}</span>
        </div>
      </body>
    </html>
  `
}