type CommitteeMember = {
  name: string
  din: string
  designation: string
}

type CsrCommitteeRecordData = {
  companyName: string
  cin: string
  financialYear: string
  members: CommitteeMember[]
  constitutionDate: string
}

export function csrCommitteeRecordTemplate(data: CsrCommitteeRecordData): string {
  return `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: Georgia, serif; background: #fff; color: #1a1a2e; padding: 60px 72px; font-size: 13px; line-height: 1.6; }
          .header { border-bottom: 3px solid #1a1a2e; padding-bottom: 20px; margin-bottom: 36px; display: flex; justify-content: space-between; align-items: flex-end; }
          .header h1 { font-size: 20px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; }
          .header p { font-size: 11px; color: #555; margin-top: 4px; }
          .header-right { font-size: 11px; color: #555; text-align: right; }
          .section { margin-bottom: 32px; }
          .section-title { font-size: 10px; font-weight: bold; letter-spacing: 2px; text-transform: uppercase; color: #888; margin-bottom: 12px; padding-bottom: 4px; border-bottom: 1px solid #e0e0e0; }
          .field-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px 32px; margin-bottom: 24px; }
          .field { display: flex; flex-direction: column; gap: 3px; }
          .field-label { font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #888; }
          .field-value { font-size: 14px; color: #1a1a2e; font-weight: 500; }
          table { width: 100%; border-collapse: collapse; font-size: 12px; }
          th { text-align: left; font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #888; padding: 8px 12px; border-bottom: 1px solid #e0e0e0; }
          td { padding: 12px; border-bottom: 1px solid #f0f0f0; color: #1a1a2e; }
          tr:last-child td { border-bottom: none; }
          .footer { margin-top: 60px; padding-top: 16px; border-top: 1px solid #e0e0e0; display: flex; justify-content: space-between; font-size: 10px; color: #aaa; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1>CSR Committee Record</h1>
            <p>Auto-generated by Navadrishti — Companies Act 2013, Section 135(1) | FY ${data.financialYear}</p>
          </div>
          <div class="header-right">
            Generated: ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}
          </div>
        </div>

        <div class="section">
          <div class="field-grid">
            <div class="field">
              <span class="field-label">Company</span>
              <span class="field-value">${data.companyName}</span>
            </div>
            <div class="field">
              <span class="field-label">CIN</span>
              <span class="field-value">${data.cin}</span>
            </div>
            <div class="field">
              <span class="field-label">Committee Constituted On</span>
              <span class="field-value">${data.constitutionDate}</span>
            </div>
            <div class="field">
              <span class="field-label">Financial Year</span>
              <span class="field-value">${data.financialYear}</span>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Committee Members</div>
          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>DIN</th>
                <th>Designation</th>
              </tr>
            </thead>
            <tbody>
              ${data.members.map((m, i) => `
                <tr>
                  <td>${i + 1}</td>
                  <td>${m.name}</td>
                  <td>${m.din}</td>
                  <td>${m.designation}</td>
                </tr>
              `).join("")}
            </tbody>
          </table>
        </div>

        <div class="footer">
          <span>Navadrishti Document Generation System</span>
          <span>CSR_COMMITTEE_RECORD — ${data.cin}</span>
        </div>
      </body>
    </html>
  `
}