// CSR POLICY DOCUMENT TEMPLATE

type ScheduleViiFocusArea = {
  category: string
  rationale: string
}

type CsrPolicyDocumentData = {
  companyName: string
  cin: string
  csrVision: string
  focusAreas: ScheduleViiFocusArea[]
  implementationModel: string
  governanceMechanism: string
  financialYear: string
}

export function csrPolicyDocumentTemplate(data: CsrPolicyDocumentData): string {
  return `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: Georgia, serif; background: #fff; color: #1a1a2e; padding: 60px 72px; font-size: 13px; line-height: 1.6; }
          .header { border-bottom: 3px solid #1a1a2e; padding-bottom: 20px; margin-bottom: 36px; display: flex; justify-content: space-between; align-items: flex-end; }
          .header h1 { font-size: 20px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; }
          .header p { font-size: 11px; color: #555; margin-top: 4px; }
          .header-right { font-size: 11px; color: #555; text-align: right; }
          .section { margin-bottom: 32px; }
          .section-title { font-size: 10px; font-weight: bold; letter-spacing: 2px; text-transform: uppercase; color: #888; margin-bottom: 12px; padding-bottom: 4px; border-bottom: 1px solid #e0e0e0; }
          .field { display: flex; flex-direction: column; gap: 3px; margin-bottom: 14px; }
          .field-label { font-size: 10px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; color: #888; }
          .field-value { font-size: 14px; color: #1a1a2e; font-weight: 500; }
          .prose { font-size: 13px; color: #333; line-height: 1.8; }
          .focus-area { background: #f7f8fc; border: 1px solid #e0e0e0; border-radius: 4px; padding: 14px 18px; margin-bottom: 10px; }
          .focus-area-title { font-size: 12px; font-weight: bold; color: #1a1a2e; margin-bottom: 4px; }
          .focus-area-rationale { font-size: 12px; color: #555; }
          .footer { margin-top: 60px; padding-top: 16px; border-top: 1px solid #e0e0e0; display: flex; justify-content: space-between; font-size: 10px; color: #aaa; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1>CSR Policy Document</h1>
            <p>Auto-generated by Navadrishti — Companies Act 2013, Section 135 | FY ${data.financialYear}</p>
          </div>
          <div class="header-right">
            Generated: ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}
          </div>
        </div>

        <div class="section">
          <div class="field">
            <span class="field-label">Company</span>
            <span class="field-value">${data.companyName}</span>
          </div>
          <div class="field">
            <span class="field-label">CIN</span>
            <span class="field-value">${data.cin}</span>
          </div>
        </div>

        <div class="section">
          <div class="section-title">CSR Vision</div>
          <p class="prose">${data.csrVision}</p>
        </div>

        <div class="section">
          <div class="section-title">Focus Areas (Schedule VII)</div>
          ${data.focusAreas.map(f => `
            <div class="focus-area">
              <div class="focus-area-title">${f.category}</div>
              <div class="focus-area-rationale">${f.rationale}</div>
            </div>
          `).join("")}
        </div>

        <div class="section">
          <div class="section-title">Implementation Model</div>
          <p class="prose">${data.implementationModel}</p>
        </div>

        <div class="section">
          <div class="section-title">Governance Mechanism</div>
          <p class="prose">${data.governanceMechanism}</p>
        </div>

        <div class="footer">
          <span>Navadrishti Document Generation System</span>
          <span>CSR_POLICY_DOCUMENT — ${data.cin}</span>
        </div>
      </body>
    </html>
  `
}